/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package userInteface;

import Health_System.CommunityDirectory;
import Health_System.Person;
import Health_System.PersonDirectory;
import userInteface.Patient.PatientManagerWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import userInteface.Patient.ManagePatientsJPanel;
import userInteface.Patient.ManageVitalSignsJPanel;
import userInteface.Person.ManagePersonsJPanel;
import userInterface.Dashboard.HomePage;

/**
 *
 * @author Harshit
 */
public class MainJFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainJFrame
     */
    private PersonDirectory personDirectory;
    private CommunityDirectory communityDirectory;
    public MainJFrame() {
        initComponents();
        this.setSize(1100, 700);
        personDirectory= new PersonDirectory();
        communityDirectory = new CommunityDirectory();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftJPanel = new javax.swing.JPanel();
        patientManagerJButton = new javax.swing.JButton();
        managePersonsJButton = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        vitalSignManagerJButton1 = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));

        jSplitPane1.setMinimumSize(new java.awt.Dimension(700, 700));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(700, 700));

        leftJPanel.setBackground(new java.awt.Color(246, 247, 215));
        leftJPanel.setMinimumSize(new java.awt.Dimension(200, 700));
        leftJPanel.setPreferredSize(new java.awt.Dimension(200, 700));

        patientManagerJButton.setText("Manage Patients");
        patientManagerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientManagerJButtonActionPerformed(evt);
            }
        });

        managePersonsJButton.setText("Manage Person's");
        managePersonsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonsJButtonActionPerformed(evt);
            }
        });

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        vitalSignManagerJButton1.setText("Manage Vital Signs");
        vitalSignManagerJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalSignManagerJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftJPanelLayout = new javax.swing.GroupLayout(leftJPanel);
        leftJPanel.setLayout(leftJPanelLayout);
        leftJPanelLayout.setHorizontalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(vitalSignManagerJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addGroup(leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(managePersonsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(patientManagerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        leftJPanelLayout.setVerticalGroup(
            leftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(managePersonsJButton)
                .addGap(18, 18, 18)
                .addComponent(patientManagerJButton)
                .addGap(18, 18, 18)
                .addComponent(vitalSignManagerJButton1)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard)
                .addContainerGap(526, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftJPanel);

        userProcessContainer.setMinimumSize(new java.awt.Dimension(500, 700));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(500, 700));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Dashboard/Webp.net-compress-image.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(720, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(720, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(720, 500));
        userProcessContainer.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientManagerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientManagerJButtonActionPerformed
        // TODO add your handling code here:
        
        if(personDirectory.getPersonHistory().isEmpty()){
            JOptionPane.showMessageDialog(this, "No Persons found. Please add Persons",
                    "Warning", JOptionPane.INFORMATION_MESSAGE);
            ManagePersonsJPanel mpJPanel= 
                new ManagePersonsJPanel(userProcessContainer, personDirectory, communityDirectory);
            userProcessContainer.add("mpJPanel", mpJPanel);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else{
            ManagePatientsJPanel mpJPanel= 
                    new ManagePatientsJPanel(userProcessContainer, personDirectory);

            userProcessContainer.add("mpJPanel", mpJPanel);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    
    }//GEN-LAST:event_patientManagerJButtonActionPerformed

    private void managePersonsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonsJButtonActionPerformed
        // TODO add your handling code here:
        ManagePersonsJPanel mpJPanel= 
                new ManagePersonsJPanel(userProcessContainer, personDirectory, communityDirectory);
        userProcessContainer.add("mpJPanel", mpJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonsJButtonActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
         HomePage homePage = new HomePage(userProcessContainer, personDirectory, communityDirectory);
        userProcessContainer.add("homePage", homePage);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void vitalSignManagerJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalSignManagerJButton1ActionPerformed
        // TODO add your handling code here:
        
        int cnt = 0;
        for(Person person: personDirectory.getPersonHistory()){
            if(person.getPatient() != null){
                cnt=1;
            }
        }
        if(personDirectory.getPersonHistory().isEmpty()){
            JOptionPane.showMessageDialog(this, "No Persons found. Please add Persons.",
                    "Warning", JOptionPane.INFORMATION_MESSAGE);
            ManagePersonsJPanel mpJPanel= 
                new ManagePersonsJPanel(userProcessContainer, personDirectory, communityDirectory);
            userProcessContainer.add("mpJPanel", mpJPanel);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else if(cnt == 0){
            JOptionPane.showMessageDialog(this, "No Patients found. Please add Patient.",
                "Warning", JOptionPane.INFORMATION_MESSAGE);

            ManagePatientsJPanel mpJPanel= 
                    new ManagePatientsJPanel(userProcessContainer, personDirectory);

            userProcessContainer.add("mpJPanel", mpJPanel);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        else{
            ManageVitalSignsJPanel mvsJPanel=
                    new ManageVitalSignsJPanel(userProcessContainer, personDirectory);
            userProcessContainer.add("mvsJPanel", mvsJPanel);
            CardLayout layout=(CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_vitalSignManagerJButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftJPanel;
    private javax.swing.JButton managePersonsJButton;
    private javax.swing.JButton patientManagerJButton;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JButton vitalSignManagerJButton1;
    // End of variables declaration//GEN-END:variables
}
